version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/usr/src/App-netflix/data

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

  tests:
    build:
      context: .
      dockerfile: Dockerfile.server
    entrypoint: ["/usr/src/App-netflix/build/runTests"]
    depends_on:
      - server
